import { NickName, Weapon, UnseenText, ShintaiText, ClassFeature, Feature } from './types';

import { rollDice } from './utils';

export const classes: string[] = [
    "Forgotten Ronin",
    "Erudite Samurai",
    "Drunken Monk",
    "Corrupted Shinobi",
    "Onmyoji",
    "Bakuto",
    "Yamabushi",
    "Wild Dancer",
    "Reckless Sumo",
    "Sword Saint",
];

export const firstNames: string[] = [
    "Himura",
    "Daichi",
    "Eiko",
    "Genji",
    "Mizu",
    "Isamu",
    "Toyo",
    "Ryoma",
    "Michiko",
    "Tomoe",
    "Osamu",
    "Rei",
    "Sachi",
    "Saito",
    "Ume",
    "Yori",
    "Zen",
    "Arata",
    "Jiro",
    "Musashi",
];

export const lastNames: string[] = [
    "Battosai",
    "Chiba",
    "Fujiwara",
    "Hattori",
    "Ito",
    "Matsamune",
    "Sakura",
    "Sakamoto",
    "Okada",
    "Hajime",
    "Takahashi",
    "Uesugi",
    "Yamagata",
    "Yojimbo",
    "Akiyama",
    "Fujimoto",
    "Miyamoto",
    "Ishikawa",
    "Kitano",
    "Matsushita",
];

export const nickNames: NickName[] = [
    { english: "Hawk Eye", japanese: "Taka no Me", kanji: "\u9DF9\u306E\u76EE" },
    { english: "Dragon of the Sea", japanese: "Umi no Tatsu", kanji: "\u6D77\u306E\u7ADC" },
    { english: "Thunder Fang", japanese: "Kaminari no Kiba", kanji: "\u96F7\u306E\u7259" },
    { english: "River God", japanese: "Kawa no Kami", kanji: "\u5DDD\u306E\u795E" },
    { english: "Mountain Wind", japanese: "Yama no Kaze", kanji: "\u5C71\u306E\u98A8" },
    { english: "Sword Saint of the Wind", japanese: "Kaze no Kensei", kanji: "\u98A8\u306E\u5263\u8056" },
    { english: "Demon of the Fog", japanese: "Kiri no Oni", kanji: "\u9727\u306E\u9B3C" },
    { english: "Tiger of Hell", japanese: "Jigoku no Tora", kanji: "\u5730\u7344\u306E\u864E" },
    { english: "Fox of the Night", japanese: "Yoru no Kitsune", kanji: "\u591C\u306E\u72D0" },
    { english: "Black Fang", japanese: "Kuroi Kiba", kanji: "\u9ED2\u3044\u7259" },
    { english: "Tiger Demon", japanese: "Tora no Oni", kanji: "\u864E\u306E\u9B3C" },
    { english: "Cat's Paw", japanese: "Neko no Te", kanji: "\u732B\u306E\u624B" },
    { english: "Wind Tengu", japanese: "Kaze no Tengu", kanji: "\u98A8\u306E\u5929\u72D7" },
    { english: "Man Slayer", japanese: "Hitokiri", kanji: "\u4EBA\u65AC\u308A" },
    { english: "Knight of Darkness", japanese: "Yami no Kishi", kanji: "\u95C7\u306E\u9A0E\u58EB" },
    { english: "Monster Boss", japanese: "Bakemono no Oyabun", kanji: "\u5316\u7269\u306E\u89AA\u5206" },
    { english: "Flower Geisha", japanese: "Hana no Geisha", kanji: "\u82B1\u306E\u82B8\u8005" },
    { english: "Warrior of Thunder", japanese: "Kaminari no Senshi", kanji: "\u96F7\u306E\u6226\u58EB" },
    { english: "Ghostly Wanderer", japanese: "Yurei no Tomurai", kanji: "\u5E7D\u970A\u306E\u5F14\u3044" },
    { english: "Black Shadow", japanese: "Kuroi Kage", kanji: "\u9ED2\u3044\u5F71" },
];

export const carryMap = new Map<number, string>([
    [1, "Empty-handed"],
    [2, "Empty-handed"],
    [3, "<strong style='color:#ECCF18;'>Backpack</strong> up to 7 small items"],
    [4, "<strong style='color:#ECCF18;'>Sack</strong> up to 10 small items"],
    [5, "<strong style='color:#ECCF18;'>Small wagon</strong>"],
    [6, "<strong style='color:#ECCF18;'>Trusty pack animal</strong>"],
]);

export const equipmentMap = new Map<number, string>([
    [1, "<strong style='color:#ECCF18;'>Rope</strong> 30 ft"],
    [2, "5 <strong style='color:#ECCF18;'>Torches</strong>"],
    [3, "<strong style='color:#ECCF18;'>Lantern</strong> with oil for 6 hours"],
    [4, "<strong style='color:#ECCF18;'>Magnesium strip</strong>"],
    [5, "<strong style='color:#ECCF18;'>An Unseen Text</strong>"],
    [6, "4 <strong style='color:#ECCF18;'>Firecrackers</strong>"],
    [7, "4 <strong style='color:#ECCF18;'>Healers Kits</strong>"],
    [8, "<strong style='color:#ECCF18;'>Metal file and lockpicks</strong>"],
    [9, "<strong style='color:#ECCF18;'>Bear trap</strong> Spirit DR14 to spot, d8 damage"],
    [10, "<strong style='color:#ECCF18;'>Black powder bomb</strong> d10 damage"],
    [11, "4 <strong style='color:#ECCF18;'>Snake venom shuriken</strong> Resilience DR12 or d8 damage"],
    [12, "<strong style='color:#ECCF18;'>Silver talisman</strong> defence DR against yokai DR10"],
]);

export const startingWeaponsMap = new Map<number, Weapon>([
    [1, { name: "Shuriken", damage: "d4", amount: "(x10)" }],
    [2, { name: "Tanto", damage: "d4" }],
    [3, { name: "Yumi", damage: "d6", amount: "(Spirit+10 arrows)" }],
    [4, { name: "Bo Staff", damage: "d6" }],
    [5, { name: "Naginata", damage: "d8" }],
    [6, { name: "Kusarigama", damage: "d6", amount: "(melee/ranged)" }],
    [7, { name: "Wakizashi", damage: "d6" }],
    [8, { name: "Nunchaku", damage: "d6" }],
    [9, { name: "Tanegashima", damage: "d8", amount: "(Spirit+5 bullets)" }],
    [10, { name: "Katana", damage: "d10" }],
]);

export const unseenTextsMap = new Map<number, UnseenText>([
    [1, { title: "Whirlwind Blade", description: "Unleash a flurry (d4) of air strikes against a single enemy, dealing d6 damage per hit." }],
    [2, { title: "Soothing Breeze", description: "Heal d6 HP for yourself or an ally." }],
    [3, { title: "Thundering Roar", description: "Stun a single enemy for 1 round." }],
    [4, { title: "Eagle Eye", description: "Gain +4 to hit for your next attack." }],
    [5, { title: "Shadow Step", description: "Instantly move to any visible location." }],
    [6, { title: "Burning Blade", description: "Ignite your weapon, dealing an extra d4 damage with each hit for d6 rounds." }],
    [7, { title: "Steel Barrier", description: "Gain +2 to Swiftness tests for defence for d6 rounds." }],
    [8, { title: "Spectral Guardian", description: "Summon a skeletal ronin to fight alongside you for d6 rounds." }],
    [9, { title: "Soul Drain", description: "Deal d8 damage and gain that much HP for yourself (can take you above max HP)." }],
    [10, { title: "Void Blast", description: "Unleash a blast of negative energy that deals d8 damage to all enemies you can see." }],
]);

export const shintaiTextsMap = new Map<number, ShintaiText>([
    [1, { title: "Blessing of the Gods", description: "Restore d10 HP to d2 creatures." }],
    [2, { title: "Grace of Redemption", description: "A creature of your choice gains +d6 on one roll." }],
    [3, { title: "Speak with the Departed", description: "Ask three questions to a deceased creature." }],
    [4, { title: "Spirit Shield", description: "A creature of your choice gains 2d6 extra HP for d3 rounds." }],
    [5, { title: "Visions of the Beyond", description: "One creature, dead for no more than a week, is awakened with terrible memories." }],
    [6, { title: "Bestial Communion", description: "You may speak with animals for d20 minutes." }],
    [7, { title: "Divine Illumination", description: "Light or darkness for 3d10 minutes." }],
    [8, { title: "Pure Insight", description: "You find all traps in your path for 2d10 minutes." }],
    [9, { title: "Holy Retribution", description: "d4 creatures lose d8 HP each." }],
    [10, { title: "Word of the Gods", description: "One creature blindly obeys a single command." }],
]);

export const brokenBodiesMap = new Map<number, string>([
    [1, "always staring with a glazed expression"],
    [2, "covered in scars or wounds, some of which are infected"],
    [3, "missing a limb, using a makeshift prosthesis"],
    [4, "emaciated and frail, with sunken eyes and greyish skin"],
    [5, "severely burned on the face and hands, using a mask to hide them"],
    [6, "deaf in one ear, struggling to hear from the other"],
    [7, "missing teeth, some rotten, speaking with a lisp"],
    [8, "crippled, walking with a limp or hunchbacked"],
    [9, "covered in boils or blisters, constantly scratching"],
    [10, "persistently cough and wheezing"],
    [11, "covered in insect bites"],
    [12, "missing your tongue"],
    [13, "suffering from nervous system damage, making youe hands shake and twitch"],
    [14, "severely obese or suffering from malnutrition, either way you are always hungry"],
    [15, "missing fingers or toes"],
    [16, "breathing heavily and snoring loudly because of your broken nose"],
    [17, "permanently scowling or smiling, making social interaction difficult"],
    [18, "suffering from a chronic skin condition, leaving skin flaky or weeping"],
    [19, "blind or suffering from vision problems"],
    [20, "not very clean, with cracked, discoloured nails and signs of fungal infection"],
]);

export const grimChroniclesMap = new Map<number, string>([
    [1, "fled from a powerful and dangerous clan and are constantly on the run."],
    [2, "have a powerful enemy who wants you dead at all costs."],
    [3, "possess a rare and valuable artifact that is coveted by many."],
    [4, "are under a terrible curse that cannot be lifted."],
    [5, "once betrayed a close friend and have been wracked with guilt ever since."],
    [6, "are plagued by haunting visions of a dark future."],
    [7, "have a shadowy past that is slowly catching up with you."],
    [8, "are haunted by a vengeful spirit that will not rest until it gets what it wants."],
    [9, "are the only survivor of a massacre that you cannot forget."],
    [10, "have a powerful addiction that is slowly destroying you."],
    [11, "have angered a powerful spirit that is now out for revenge."],
    [12, "are followed by a strange, unexplainable phenomenon that brings chaos and destruction wherever you go."],
    [13, "are hunted by a terrifying monster that you cannot defeat."],
    [14, "are haunted by a dark secret that, if revealed, could destroy everything you hold dear."],
    [15, "have made a dangerous enemy of an influential clan."],
    [16, "have made a deal with a malevolent entity that is slowly taking over your mind and body."],
    [17, "are cursed with the ability to see the worst in people and cannot help but voice your thoughts."],
    [18, "are plagued by unexplainable nightmares that are slowly driving you insane."],
    [19, "are cursed with an insatiable hunger that can never be sated."],
    [20, "have been marked by a dark force that will stop at nothing to claim your soul."],
]);

export const badHabitsMap = new Map<number, string>([
    [1, "compulsively hoard any small trinkets you come across, often to the detriment of your party."],
    [2, "have a crippling fear of enclosed spaces or the dark."],
    [3, "have an urge to speak your mind, even if it means making enemies or getting into trouble."],
    [4, "are addicted to a particular substance and go to great lengths to get your fix."],
    [5, "have a habit of stealing things, even when it's not beneficial."],
    [6, "have anger management issues. Tend to lash out violently."],
    [7, "have chronic insomnia."],
    [8, "are extremely paranoid. You make up conspiracy theories, even when they have no basis in reality."],
    [9, "have a terrible memory, often forget important details or information."],
    [10, "are a persistent procrastinator."],
    [11, "are obsessed with counting and arranging objects."],
    [12, "often mmumble to yourself, even in public."],
    [13, "are always losing important items."],
    [14, "need to keep your weapons and tools CLEAN."],
    [15, "tell overly long and irrelevant tales in conversation."],
    [16, "collect ears to whisper secrets into."],
    [17, "are constantly fidgeting. Just can’t sit still."],
    [18, "have a habit of making loud, nervous sneezes."],
    [19, "hate being touched."],
    [20, "cannot help but steal food from everyone then hoard it."],
]);

export const awfulAfflictionsMap = new Map<number, string>([
    [1, "Paranoid."],
    [2, "Sadistic."],
    [3, "Narcissistic."],
    [4, "Compulsive liar."],
    [5, "Self-destructive."],
    [6, "Envious."],
    [7, "Antisocial."],
    [8, "Addicted."],
    [9, "Short-tempered."],
    [10, "Greedy."],
    [11, "Pessimistic."],
    [12, "Manipulative."],
    [13, "Careless."],
    [14, "Aggressive."],
    [15, "Insecure."],
    [16, "Hedonistic."],
    [17, "Fanatical."],
    [18, "Hypocritical."],
    [19, "Unreliable."],
    [20, "Delusional."],
]);

export const classFeatures: { [key: string]: ClassFeature } = {
    "Forgotten Ronin": {
        modifiers: { swiftness: 2, spirit: -2, vigor: 2, resilience: 2, honour: -1 },
        calculateHitPoints: (abilities) => Math.max(1, abilities.resilience + rollDice(1, 10)),
        rollRyo: () => rollDice(1, 6) * 10,
        rollVirtues: () => rollDice(1, 2),
        virtuesDice: "d2",
        weapons: [{ name: "Worn katana", damage: "d8" }],
        startingEquipment: ["Traveling clothes", "Straw hat"],
        features: new Map<number, Feature>([
            [1, { title: "Ronin’s Resolve", description: "The Forgotten Ronin can draw upon their inner strength and resolve in times of great need. Once per day, they may roll d6 and add the result to any one roll they make." }],
            [2, { title: "Sword Master", description: "A master of the blade, wielding their sword with deadly precision. They may add their Vigor modifier to damage rolls made with melee weapons." }],
            [3, { title: "Masterless", description: "If the Forgotten Ronin’s honour score is below 10 they may Parry at DR12." }],
            [4, { title: "Bushi's Blade", description: "When both the Rōnin and an enemy are wielding a Katana or Wakizashi the attack and defence DR is lowered by 2." }],
            [5, { title: "Protector", description: "The Forgotten Ronin is fiercely protective of their allies and will go to great lengths to defend them. Once per combat, they may protect an ally, adding +2 to their defence against all attacks until the end of the Ronin’s next turn." }],
            [6, { title: "Haunted Blade", description: "Once per combat, make a sacrifice to the blade; anything from losing d4 HP to discarding an important item. On the next attack with the blade, roll twice and take the higher roll, the strike deals an extra d8 damage. After the strike, the blade attacks a random target including the Ronin and allies, until the end of the Ronin’s next turn." }],
        ]),
        honourTenets: { title: "The Ronin’s Creed", tenetsList: ["Resilience", "Freedom", "Personal Mastery", "Empathy", "Discipline", "Dignity"] },
    },
    "Erudite Samurai": {
        modifiers: { swiftness: -1, spirit: -1, vigor: 2, resilience: 1, honour: 2 },
        calculateHitPoints: (abilities) => Math.max(1, abilities.resilience + rollDice(1, 8)),
        rollRyo: () => rollDice(3, 6) * 10,
        rollVirtues: () => rollDice(1, 2),
        virtuesDice: "d2",
        weapons: [{ name: "Fine Katana", damage: "d10" }, { name: "Wakizashi", damage: "d6" }],
        startingEquipment: ["Collection of books and papers"],
        features: new Map<number, Feature>([
            [1, { title: "Scholarly Training", description: "The Erudite Samurai has received extensive training in the arts of literature, philosophy, and the sciences. If in honourable standing (above 10 Honour) they may add +4 to a damage roll once per day." }],
            [2, { title: "Philosophy of War", description: "Once per combat, predict the next move of the enemy and gain a +2 bonus to an roll against that opponent. This ability can only be used if they have had at least one round to observe their opponent's fighting style." }],
            [3, { title: "Tactical Genius", description: " A master of strategy and tactics. They may use their honour score if in honourable standing (Honour 10 or above) to gain an advantage in combat, reducing the DR of a parry to DR12." }],
            [4, { title: "Precise Strike", description: "Trained to strike with precision, finding the weaknesses in their opponents' defences. Once per combat encounter, they may add a bonus to their attack roll equal to their Vigor modifier." }],
            [5, { title: "Intimidating Presence", description: "Knowledge and training make them a formidable opponent. Once per day, they can intimidate their enemies, lowering the DR of their next attack by 4." }],
            [6, { title: "Zen Focus", description: "Once per day, they can enter a state of zen-like focus, granting them a +1 bonus to all ability rolls for a duration of 10 minutes." }],
        ]),
        honourTenets: { title: "Bushido", tenetsList: ["Courage", "Honesty", "Honour", "Loyalty", "Self-Control", "Self-Sacrifice"] },
    },
    "Drunken Monk": {
        modifiers: { swiftness: 2, spirit: 2, vigor: 1, resilience: -2, honour: -1 },
        calculateHitPoints: (abilities) => Math.max(1, abilities.resilience + rollDice(1, 8)),
        rollRyo: () => rollDice(1, 6) * 10,
        rollVirtues: () => rollDice(1, 4),
        virtuesDice: "d4",
        weapons: [{ name: "Brass knuckles", damage: "d4" }],
        startingEquipment: ["Monk's robes and sandals", "<strong style='color:#ECCF18;'>Gourd of sake</strong> d4 uses"],
        features: new Map<number, Feature>([
            [1, { title: "Drunken Fist", description: "The Drunken Monk fights with an unpredictable, fluid style that confounds opponents. They may add their Spirit modifier when making unarmed attacks." }],
            [2, { title: "Five Finger Death Punch", description: "Once per session, choose to strike an opponent with a precision unarmed attack that targets pressure points, dealing an additional 6d4 on a success and stunning the target." }],
            [3, { title: "Roadhouse", description: "Make a brutal attack against an opponent's throat potentially killing them outright. Before making an attack, Test Spirit DR14. The attack requires the monk to make a successful attack and may only be used on a surprised opponent." }],
            [4, { title: "Flame Fist", description: "Knuckles imbued with mystical fire, dealing 1d4 additional fire damage and potentially setting targets on fire. The Monk may only use this ability a limited number of times per day (Spirit +1)." }],
            [5, { title: "Sake Style", description: "When the Drunken Monk is under the effects of alcohol, they gain a temporary +2 bonus to their melee attacks and defence." }],
            [6, { title: "Drunken Master", description: "Turn any item into a weapon, increasing the damage from a d4 to d6. Additionally, they have a +1 bonus to initiative rolls while drunk." }],
        ]),
        honourTenets: { title: "Noble Truths", tenetsList: ["Simplicity", "Harmony", "Compassion", "Perseverance", "Serenity", "Honesty"] },
    },
    "Corrupted Shinobi": {
        modifiers: { swiftness: 2, spirit: 2, vigor: -1, resilience: 1, honour: -2 },
        calculateHitPoints: (abilities) => Math.max(1, abilities.resilience + rollDice(1, 8)),
        rollRyo: () => rollDice(2, 6) * 10,
        rollVirtues: () => rollDice(1, 2),
        virtuesDice: "d2",
        weapons: [{ name: "Pair of kusarigama", damage: "d6", amount: "(melee/ranged)" }, { name: "Shuriken", damage: "d4", amount: "(x10)" }],
        startingEquipment: ["Dark, unremarkable clothing", "<strong style='color:#ECCF18;'>Small vial of poison</strong> d6 uses, d4 damage for d4 rounds"],
        features: new Map<number, Feature>([
            [1, { title: "Corrupted Techniques", description: "Various forbidden techniques that allow manipulation of shadows and infliction of horrific curses. Once per day, they can choose one of the following effects: create a pool of darkness to hide in or curse an enemy to take ongoing damage (d4 per round)." }],
            [2, { title: "Poison Master", description: "An expert in crafting and applying deadly poisons. They can create one dose of poison during a short rest. Poisons created this way deal an additional d4 damage." }],
            [3, { title: "Smoke Screen", description: "Once per day, the shinobi can create a dense cloud of smoke that provides cover and obscures vision. The smoke lasts for d6 rounds." }],
            [4, { title: "Betrayer's Blade", description: "The Corrupted Shinobi carries a blade that is infused with dark magic and has the ability to absorb the life force of their enemies. Once per day, they can use this ability to deal an additional d8 damage and heal themselves for the same amount." }],
            [5, { title: "Shadow Step", description: "Teleport a short distance by stepping into the shadows. They can use this ability to teleport to a nearby shadowy area. The Shinobi may only use this ability a limited number of times per day (Swiftness +1)." }],
            [6, { title: "Dark Illusion", description: "Once per combat, they can create an illusory double of themselves, causing enemies to attack the wrong target. When the Shinobi is hit, roll a d6; on an even number the enemy hits the Shinobi, on an odd number it hits the illusion causing it to disappear." }],
        ]),
        honourTenets: { title: "The Unseen Virtues", tenetsList: ["Deception", "Ruthlessness", "Loyalty", "Discretion", "Adaptability", "Perseverance"] },
    },
    Onmyoji: {
        modifiers: { swiftness: -1, spirit: 3, vigor: 2, resilience: -1, honour: 0 },
        calculateHitPoints: (abilities) => Math.max(1, abilities.resilience + rollDice(1, 8)),
        rollRyo: () => rollDice(1, 6) * 10,
        rollVirtues: () => rollDice(1, 4),
        virtuesDice: "d4",
        weapons: [{ name: "Kiseru", damage: "d4" }],
        startingEquipment: ["Robes and talismans"],
        features: new Map<number, Feature>([
            [1, { title: "Divining Rod", description: "A rod carved from a sacred tree that vibrates and hums when danger is near. When in use, the rod will point in the direction of any nearby threats. Once per day, the Onmyoji can ask the rod a yes or no question and receive a clear answer." }],
            [2, { title: "Ofuda Talisman", description: "A sheet of paper inscribed with protective symbols that can be used to ward off evil spirits or curses. The talisman can be used once per day to protect against a single supernatural attack or effect. Test Spirit DR12 to activate the talisman and negate the effect." }],
            [3, { title: "Spirit Beacon", description: "Once per day, create a glowing beacon that draws enemies towards it. Test Spirit DR12. On a success, all enemies in the area are drawn to the beacon, distracting them from attacking the Onmyoji. On a fail, the beacon attracts all enemies to the Onmyoji. The beacon lasts for d6 rounds." }],
            [4, { title: "Shadow Binding", description: "Attempt to bind an enemy to its shadow, rendering them immobile. To use this ability, Test Spirit DR12. On a success, the enemy is unable to move until the end of the Onmyoji's next turn. The Onmyoji may only use this ability a limited number of times per day (Spirit +1)." }],
            [5, { title: "Text of Exorcism", description: "A text containing powerful incantations and symbols that can be used to banish evil spirits or demons. Once per day, the Onmyoji must Test Spirit DR14 to activate the text, which can banish a single spirit or demon (cannot be used in Yomi)." }],
            [6, { title: "Mirror of Reflection", description: "A handheld mirror inscribed with runes that can be used to reflect hostile spells or attacks. Once per day, Test Spirit DR12 to use the mirror, reflecting any spell or attack directed at them. This deals the attack’s damage back to the attacker." }],
        ]),
        honourTenets: { title: "The Rules of the Divine", tenetsList: ["Respect for Nature", "Balance", "Wisdom", "Compassion", "Patience", "Perseverance"] },
    },
    Bakuto: {
        modifiers: { swiftness: -2, spirit: 2, vigor: 2, resilience: -1, honour: 1 },
        calculateHitPoints: (abilities) => Math.max(1, abilities.resilience + rollDice(1, 10)),
        rollRyo: () => rollDice(3, 6) * 10,
        rollVirtues: () => rollDice(1, 4),
        virtuesDice: "d4",
        weapons: [{ name: "Tanto", damage: "d4" }],
        startingEquipment: ["Stylish, flamboyant clothing", "Loaded dice and marked cards"],
        features: new Map<number, Feature>([
            [1, { title: "Gambling Luck", description: "Bakuto can sense when a game is rigged, or someone is cheating. They get +2 to Spirit tests when gambling or playing games of chance. They can also re-roll any one roll, once per day." }],
            [2, { title: "Sucker Punch", description: "Take a swing before they know what hit ‘em. Deal double damage with their first strike in a round." }],
            [3, { title: "Dirty Tricks", description: "Pull a fast one to gain the advantage. Once per combat, add +2 to any attack or defence roll by using deception, trickery or surprise." }],
            [4, { title: "Sleight of Hand", description: "The art of pickpocketing, intimidation, and thievery. They get +4 to Spirit tests when attempting these actions." }],
            [5, { title: "Double Strike", description: "A master of dual wielding. Make two melee attacks in a single turn, but each attack suffers a -2 penalty to the attack roll." }],
            [6, { title: "Feint", description: "Choose to forgo their attack on their turn and instead Test Spirit DR10. If successful, the Bakuto gains a +4 to their next attack also dealing +4 damage." }],
        ]),
        honourTenets: { title: "The Gambler’s Way", tenetsList: ["Honour Among Thieves", "Resourcefulness", "Bravery", "Self-Reliance", "Camaraderie", "Adaptability"] },
    },
    Yamabushi: {
        modifiers: { swiftness: 1, spirit: 2, vigor: -1, resilience: 1, honour: 1 },
        calculateHitPoints: (abilities) => Math.max(1, abilities.resilience + rollDice(1, 8)),
        rollRyo: () => rollDice(1, 6) * 10,
        rollVirtues: () => rollDice(1, 4),
        virtuesDice: "d4",
        weapons: [{ name: "Bo Staff", damage: "d6" }],
        startingEquipment: ["Robes and sash adorned with pom-poms"],
        features: new Map<number, Feature>([
            [1, { title: "Mountain's Resolve", description: "Once per day, draw upon the spiritual energy of the mountains to gain a +4 bonus to a roll." }],
            [2, { title: "Spiritual Martial Arts", description: "Trained in a unique form of martial arts that channels spiritual energy. Once per combat, add their Spirit modifier to an attack or defence roll." }],
            [3, { title: "Mountain's Fury", description: "Once per combat, channel the wrath of the mountains into a powerful strike, dealing an additional d6 damage." }],
            [4, { title: "Ascetic's Wisdom", description: "Years of solitude have given deep insight. Once per day, may reroll a failed Spirit test." }],
            [5, { title: "Divine Guidance", description: "Call upon the spirits for guidance and protection. Once per day, perform a ritual to seek divine guidance, granting a temporary +2 bonus to one ability for the next hour." }],
            [6, { title: "Mystic's Shield", description: "Once per day, use spiritual energy to shield from harm, reducing the damage of an incoming attack to zero." }],
        ]),
        honourTenets: { title: "The Yamabushi’s Path", tenetsList: ["Enlightenment", "Harmony", "Healing", "Exorcism", "Discipline", "Tradition"] },
    },
    "Wild Dancer": {
        modifiers: { swiftness: -1, spirit: 2, vigor: 2, resilience: -2, honour: -1 },
        calculateHitPoints: (abilities) => Math.max(1, abilities.resilience + rollDice(1, 8)),
        rollRyo: () => rollDice(1, 6) * 10,
        rollVirtues: () => rollDice(1, 2),
        virtuesDice: "d2",
        weapons: [{ name: "Katana", damage: "d8" }, { name: "Tanegashima", damage: "d8", amount: "(Spirit+5 bullets)" }],
        startingEquipment: ["Flashy, decorative kimono"],
        features: new Map<number, Feature>([
            [1, { title: "Untamed Ferocity", description: "Once per combat, enter a state of untamed ferocity for rounds equal to Vigor modifier. +1 bonus to attack/defence, matchlock pistol deals additional d4 damage. No Parry ability during this state." }],
            [2, { title: "Two-Weapon Fighting", description: "Skilled in fighting with a weapon in each hand. Once per day, attack twice in a round with both gun and katana." }],
            [3, { title: "Dancing Defence", description: "Use graceful movements to dodge attacks. Once per day, dodge an attack that would have hit." }],
            [4, { title: "Shooting Star", description: "Once per combat, perform a flashy attack with the pistol, reducing DR to attack that enemy by 4 for the next round." }],
            [5, { title: "Sword Dance", description: "Once per day, unleash a flurry of sword strikes, dealing an extra 2d6 damage." }],
            [6, { title: "Wild Spirit", description: "Unpredictable nature makes it hard for enemies to anticipate actions. Once per combat, reroll a failed attack or defence roll." }],
        ]),
        honourTenets: { title: "The Dancer’s Code", tenetsList: ["Expression", "Rhythm", "Passion", "Grace", "Courage", "Innovation"] },
    },
    "Reckless Sumo": {
        modifiers: { swiftness: -2, spirit: -1, vigor: 3, resilience: 2, honour: 1 },
        calculateHitPoints: (abilities) => Math.max(1, abilities.resilience + rollDice(1, 12)),
        rollRyo: () => rollDice(1, 6) * 10,
        rollVirtues: () => rollDice(1, 2),
        virtuesDice: "d2",
        weapons: [{ name: "Hand chalk", damage: "d8" }],
        startingEquipment: ["Traditional Sumo clothing"],
        features: new Map<number, Feature>([
            [1, { title: "Iron Body", description: "A Sumo’s body is like a fortress. Once per day, they may shrug off an attack that would have damaged them." }],
            [2, { title: "Sumo Slam", description: "Uses superior strength and mass to deliver a powerful slam attack. Once per combat, add twice Vigor modifier to a melee attack roll." }],
            [3, { title: "Mountain's Grasp", description: "Roll 2d6+Vigor. If higher than target's morale, they are grappled, unable to attack/move until start of Sumo’s next turn. Ends early if Sumo moved or unconscious." }],
            [4, { title: "Ring Out", description: "Once per combat, push an enemy out of the immediate combat zone, stopping them from melee attacks for a round." }],
            [5, { title: "Chanko Power", description: "Incredible strength from diet of chanko nabe. Once per day, tap into this power for a +6 on any Vigor test." }],
            [6, { title: "Belly Bump", description: "Use girth to bump an opponent, potentially knocking them off balance. Next round, attacks against this enemy are made at +4." }],
        ]),
        honourTenets: { title: "The Sumo’s Oath", tenetsList: ["Endurance", "Strength", "Patience", "Respect", "Discipline", "Tradition"] },
        foodConsumption: "The Sumo consumes 2 Food when resting instead of 1",
    },
    "Sword Saint": {
        modifiers: { swiftness: 2, spirit: -1, vigor: 2, resilience: 1, honour: 1 },
        calculateHitPoints: (abilities) => Math.max(1, abilities.resilience + rollDice(1, 8)),
        rollRyo: () => rollDice(1, 6) * 10,
        rollVirtues: () => rollDice(1, 2),
        virtuesDice: "d2",
        weapons: [{ name: "Odachi", damage: "d10" }],
        startingEquipment: ["Empty-handed"],
        features: new Map<number, Feature>([
            [1, { title: "Artful Execution", description: "Master of weapon, capable of precision strikes, ignoring opponent's armour or defences once per combat." }],
            [2, { title: "Unyielding Focus", description: "Heightened concentration in battle, reducing all incoming damage by half for one round, once per combat." }],
            [3, { title: "Blade's Spirit", description: "Once per session, pour spirit into a strike, adding Honour score to the damage roll." }],
            [4, { title: "Ancestral Weapon", description: "Weapon passed down through generations. Once per day, call upon ancestral spirits for a reroll on attack roll." }],
            [5, { title: "Harmonic Duel", description: "Predict opponent's move in a duel, gaining advantage on next attack, defence, or riposte, once per duel." }],
            [6, { title: "Unyielding Discipline", description: "Intimidate enemies, lowering DR of next attack by -4, once per day." }],
        ]),
        honourTenets: { title: "The Sword Saint’s Discipline", tenetsList: ["Precision", "Mastery", "Discipline", "Valour", "Respect", "Legacy"] },
    },
};

// function rollDice(arg0: number, arg1: number): any {
//     throw new Error('Function not implemented.');
// }
